{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uvoo-sqviz.fullname" . }}
  labels:
    {{- include "uvoo-sqviz.labels" . | nindent 4 }}
type: Opaque
stringData:
  SQVIZ_CLICKHOUSE_PASSWORD: {{ .Values.secret.clickhousePassword | quote }}
  SQVIZ_SECRET_CLICKHOUSE_DEFAULT: {{ .Values.secret.clickhouseDefaultSecret | quote }}
  SQVIZ_OIDC_KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.keycloakClientSecret | quote }}
  SQVIZ_ALERT_SMTP_PASSWORD: {{ .Values.secret.alertSmtpPassword | quote }}
  SQVIZ_SECRETS_ENCRYPTION_KEY: {{ .Values.secret.secretsEncryptionKey | quote }}
{{- end }}
