{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uvoo-dbviz.fullname" . }}
  labels:
    {{- include "uvoo-dbviz.labels" . | nindent 4 }}
type: Opaque
stringData:
  DBVIZ_CLICKHOUSE_PASSWORD: {{ .Values.secret.clickhousePassword | quote }}
  DBVIZ_OIDC_KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.keycloakClientSecret | quote }}
{{- end }}

