{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uvoo-sqviz.fullname" . }}
  labels:
    {{- include "uvoo-sqviz.labels" . | nindent 4 }}
type: Opaque
stringData:
  SQVIZ_CLICKHOUSE_PASSWORD: {{ .Values.secret.clickhousePassword | quote }}
  SQVIZ_SECRET_CLICKHOUSE_DEFAULT: {{ .Values.secret.clickhouseDefaultSecret | quote }}
  SQVIZ_POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  SQVIZ_POSTGREST_JWT_SECRET: {{ .Values.secret.postgrestJwtSecret | quote }}
  SQVIZ_KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secret.keycloakAdminPassword | quote }}
  SQVIZ_OIDC_KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.keycloakClientSecret | quote }}
  SQVIZ_ALERT_SMTP_PASSWORD: {{ .Values.secret.alertSmtpPassword | quote }}
  SQVIZ_SECRETS_ENCRYPTION_KEY: {{ .Values.secret.secretsEncryptionKey | quote }}
  PGRST_DB_URI: {{ printf "postgres://sqviz:%s@%s:5432/sqviz" .Values.secret.postgresPassword (include "uvoo-sqviz.postgresName" .) | quote }}
{{- end }}
